<?php
/**
 * GlobalApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Catalogs
 *
 * This API allows you to manage your catalogs
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * GlobalApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GlobalApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for catalogGetBeezUPColumns
     *
     * Get the BeezUP columns.
     *
     */
    public function testCatalogGetBeezUPColumns()
    {

    }

    /**
     * Test case for createChannelCatalog
     *
     * Create a new channel catalog.
     *
     */
    public function testCreateChannelCatalog()
    {

    }

    /**
     * Test case for deleteChannelCatalog
     *
     * Delete the channel catalog.
     *
     */
    public function testDeleteChannelCatalog()
    {

    }

    /**
     * Test case for getChannelCatalog
     *
     * Get the channel catalog information.
     *
     */
    public function testGetChannelCatalog()
    {

    }

    /**
     * Test case for getChannelCatalogs
     *
     * List all your current channel catalogs.
     *
     */
    public function testGetChannelCatalogs()
    {

    }

    /**
     * Test case for getChannelCategories
     *
     * Get channel categories.
     *
     */
    public function testGetChannelCategories()
    {

    }

    /**
     * Test case for getChannelColumns
     *
     * Get channel columns.
     *
     */
    public function testGetChannelColumns()
    {

    }

    /**
     * Test case for getChannelInfo
     *
     * Get channel information.
     *
     */
    public function testGetChannelInfo()
    {

    }

    /**
     * Test case for getCurrentChannels
     *
     * List all available channel for this store.
     *
     */
    public function testGetCurrentChannels()
    {

    }

    /**
     * Test case for getMarketplaceAccountsSynchronization
     *
     * Get marketplace accounts synchronization status.
     *
     */
    public function testGetMarketplaceAccountsSynchronization()
    {

    }

    /**
     * Test case for harvestAll
     *
     * Harvest orders from all marketplaces.
     *
     */
    public function testHarvestAll()
    {

    }

}
