<?php
/**
 * ChannelCatalogProductInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Catalogs
 *
 * This API allows you to manage your catalogs
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChannelCatalogProductInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description The channel catalog product information
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChannelCatalogProductInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ChannelCatalogProductInfo"
     */
    public function testChannelCatalogProductInfo()
    {

    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {

    }

    /**
     * Test attribute "overrides"
     */
    public function testPropertyOverrides()
    {

    }

    /**
     * Test attribute "disabled"
     */
    public function testPropertyDisabled()
    {

    }

    /**
     * Test attribute "category_mapped"
     */
    public function testPropertyCategoryMapped()
    {

    }

    /**
     * Test attribute "excluded"
     */
    public function testPropertyExcluded()
    {

    }

    /**
     * Test attribute "excluded_by"
     */
    public function testPropertyExcludedBy()
    {

    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {

    }

}
