<?php
/**
 * StoreHeaderLinksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Catalogs
 *
 * This API allows you to manage your catalogs
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StoreHeaderLinksTest Class Doc Comment
 *
 * @category    Class */
// * @description The action links for this store
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StoreHeaderLinksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "StoreHeaderLinks"
     */
    public function testStoreHeaderLinks()
    {

    }

    /**
     * Test attribute "get_store_link"
     */
    public function testPropertyGetStoreLink()
    {

    }

    /**
     * Test attribute "delete_store_link"
     */
    public function testPropertyDeleteStoreLink()
    {

    }

    /**
     * Test attribute "update_store_link"
     */
    public function testPropertyUpdateStoreLink()
    {

    }

    /**
     * Test attribute "get_shares_link"
     */
    public function testPropertyGetSharesLink()
    {

    }

}
